apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ai-document-intelligence.outputVolumeName" . }}
  labels:
    {{ include "ai-document-intelligence.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  storageClassName: {{ .Values.documentIntelligence.outputVolume.storageClassName }}
  accessModes: {{ toYaml .Values.documentIntelligence.outputVolume.accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.documentIntelligence.outputVolume.capacity }}
